#!/usr/bin/env python3
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'crates/emwin-parser/data/wmo_offices.json'
TARGET = ROOT / 'crates/emwin-parser/src/data/generated_wmo_office.rs'


def rust_string(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    rows = json.loads(SOURCE.read_text())
    rows.sort(key=lambda row: row['code'])
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')

    lines = [
        '// @generated by scripts/generate_wmo_office_data.py',
        '// Source file:',
        '// - crates/emwin-parser/data/wmo_offices.json',
        '// Do not edit manually.',
        '',
        'use super::WmoOfficeEntry;',
        '',
        f'pub const WMO_OFFICE_GENERATED_AT_UTC: &str = {rust_string(generated_at)};',
        'pub const WMO_OFFICE_SOURCE_PATH: &str = "crates/emwin-parser/data/wmo_offices.json";',
        f'pub const WMO_OFFICE_ENTRY_COUNT: usize = {len(rows)};',
        '',
        'pub static WMO_OFFICE_CATALOG: [WmoOfficeEntry; WMO_OFFICE_ENTRY_COUNT] = [',
    ]

    for row in rows:
        lines.extend([
            '    WmoOfficeEntry {',
            f'        code: {rust_string(row["code"])},',
            f'        office_name: {rust_string(row["office_name"])},',
            f'        city: {rust_string(row["city"])},',
            f'        state: {rust_string(row["state"])},',
            '    },',
        ])

    lines.extend(['];', ''])
    TARGET.write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
