#!/usr/bin/env python3

import csv
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "crates/emwin-parser/data/product_catalog.csv"
OUTPUT_PATH = REPO_ROOT / "crates/emwin-parser/src/data/generated.rs"

SOURCE_REPO = "bradsjm/nwws2mqtt"
SOURCE_PATH = "docs/weather/Product List.md"
SOURCE_COMMIT = "9687d59674638ab680aff384ae77f959133ca554"


def load_catalog():
    entries = {}
    with CATALOG_PATH.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            pil = row["pil"].strip().upper()
            wmo_prefix = row["wmo_prefix"].strip().upper()
            title = row["title"].strip()
            if not pil or not wmo_prefix or not title:
                continue
            previous = entries.get(pil)
            if previous and previous != (wmo_prefix, title):
                raise SystemExit(
                    f"conflicting catalog entry for {pil}: {previous} vs {(wmo_prefix, title)}"
                )
            entries[pil] = (wmo_prefix, title)
    return sorted(entries.items())


def rust_string(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_output(catalog):
    generated_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )

    lines = [
        "// @generated by scripts/generate_product_data.py",
        "// Source file:",
        "// - crates/emwin-parser/data/product_catalog.csv",
        "// Provenance:",
        f"// - repo: {SOURCE_REPO}",
        f"// - path: {SOURCE_PATH}",
        f"// - commit: {SOURCE_COMMIT}",
        "// Do not edit manually.",
        "",
        "use super::PilCatalogEntry;",
        "",
        f"pub const PIL_SOURCE_REPO: &str = {rust_string(SOURCE_REPO)};",
        f"pub const PIL_SOURCE_PATH: &str = {rust_string(SOURCE_PATH)};",
        f"pub const PIL_SOURCE_COMMIT: &str = {rust_string(SOURCE_COMMIT)};",
        f"pub const PIL_GENERATED_AT_UTC: &str = {rust_string(generated_at)};",
        f"pub const PIL_ENTRY_COUNT: usize = {len(catalog)};",
        "",
        "pub static PIL_CATALOG: [PilCatalogEntry; PIL_ENTRY_COUNT] = [",
    ]

    for pil, (wmo_prefix, title) in catalog:
        lines.append(
            f"    PilCatalogEntry {{ pil: {rust_string(pil)}, wmo_prefix: {rust_string(wmo_prefix)}, title: {rust_string(title)} }},"
        )

    lines.extend(
        [
            "];",
            "",
        ]
    )

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main():
    catalog = load_catalog()
    write_output(catalog)


if __name__ == "__main__":
    main()
