#!/usr/bin/env python3

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parent.parent
COUNTY_PATH = REPO_ROOT / 'crates/emwin-parser/data/ugc_counties.json'
ZONE_PATH = REPO_ROOT / 'crates/emwin-parser/data/ugc_zones.json'
OUTPUT_PATH = REPO_ROOT / 'crates/emwin-parser/src/data/generated_ugc.rs'


class UgcCatalogEntry(TypedDict):
    name: str
    latitude: float
    longitude: float


def require_str(entry: dict[str, object], code: str, key: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str):
        raise SystemExit(f'ugc entry {code} must define string field {key}')
    normalized = value.strip()
    if not normalized:
        raise SystemExit(f'ugc entry {code} has empty field {key}')
    return normalized


def require_float(entry: dict[str, object], code: str, key: str) -> float:
    value = entry.get(key)
    if not isinstance(value, (int, float)):
        raise SystemExit(f'ugc entry {code} must define numeric field {key}')
    return float(value)


def load_catalog(path: Path, expected_class: str) -> list[tuple[str, UgcCatalogEntry]]:
    raw = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(raw, dict):
        raise SystemExit(f'{path} must be an object keyed by UGC code')

    entries: dict[str, UgcCatalogEntry] = {}
    for code_key, entry in raw.items():
        if not isinstance(code_key, str):
            raise SystemExit(f'{path} keys must be strings')
        if not isinstance(entry, dict):
            raise SystemExit(f'ugc entry {code_key} must be an object')

        code = code_key.strip().upper()
        if len(code) != 6 or code[:2].isalpha() is False or code[2] != expected_class or not code[3:].isdigit():
            raise SystemExit(f'invalid UGC key in {path.name}: {code_key!r}')

        normalized: UgcCatalogEntry = {
            'name': require_str(entry, code, 'name'),
            'latitude': require_float(entry, code, 'latitude'),
            'longitude': require_float(entry, code, 'longitude'),
        }

        previous = entries.get(code)
        if previous and previous != normalized:
            raise SystemExit(f'conflicting ugc entry for {code}: {previous} vs {normalized}')
        entries[code] = normalized

    return sorted(entries.items())


def rust_string(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def rust_float(value: float) -> str:
    formatted = f'{value:.4f}'
    if '.' not in formatted:
        formatted += '.0'
    return formatted


def write_output(
    counties: list[tuple[str, UgcCatalogEntry]],
    zones: list[tuple[str, UgcCatalogEntry]],
) -> None:
    generated_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace('+00:00', 'Z')
    )

    lines = [
        '// @generated by scripts/generate_ugc_data.py',
        '// Source files:',
        '// - crates/emwin-parser/data/ugc_counties.json',
        '// - crates/emwin-parser/data/ugc_zones.json',
        '// Do not edit manually.',
        '',
        'use super::UgcLocationEntry;',
        '',
        f'pub const UGC_GENERATED_AT_UTC: &str = {rust_string(generated_at)};',
        "pub const UGC_COUNTY_SOURCE_PATH: &str = \"crates/emwin-parser/data/ugc_counties.json\";",
        "pub const UGC_ZONE_SOURCE_PATH: &str = \"crates/emwin-parser/data/ugc_zones.json\";",
        f'pub const UGC_COUNTY_ENTRY_COUNT: usize = {len(counties)};',
        f'pub const UGC_ZONE_ENTRY_COUNT: usize = {len(zones)};',
        '',
        'pub static UGC_COUNTY_CATALOG: [UgcLocationEntry; UGC_COUNTY_ENTRY_COUNT] = [',
    ]

    for code, entry in counties:
        lines.extend(
            [
                '    UgcLocationEntry {',
                f'        code: {rust_string(code)},',
                f"        name: {rust_string(entry['name'])},",
                f"        latitude: {rust_float(entry['latitude'])},",
                f"        longitude: {rust_float(entry['longitude'])},",
                '    },',
            ]
        )

    lines.extend(['];', '', 'pub static UGC_ZONE_CATALOG: [UgcLocationEntry; UGC_ZONE_ENTRY_COUNT] = ['])

    for code, entry in zones:
        lines.extend(
            [
                '    UgcLocationEntry {',
                f'        code: {rust_string(code)},',
                f"        name: {rust_string(entry['name'])},",
                f"        latitude: {rust_float(entry['latitude'])},",
                f"        longitude: {rust_float(entry['longitude'])},",
                '    },',
            ]
        )

    lines.extend(['];', ''])
    OUTPUT_PATH.write_text('\n'.join(lines), encoding='utf-8')


def main() -> None:
    counties = load_catalog(COUNTY_PATH, 'C')
    zones = load_catalog(ZONE_PATH, 'Z')
    write_output(counties, zones)


if __name__ == '__main__':
    main()
