#!/usr/bin/env python3

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TypedDict


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / 'crates/emwin-parser/data/nwslid.json'
OUTPUT_PATH = REPO_ROOT / 'crates/emwin-parser/src/data/generated_nwslid.rs'


class NwslidCatalogEntry(TypedDict):
    state_code: str
    stream_name: str
    proximity: str
    place_name: str
    latitude: float
    longitude: float


def require_str(entry: dict[str, object], nwslid: str, key: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str):
        raise SystemExit(f'nwslid entry {nwslid} must define string field {key}')
    normalized = value.strip()
    if not normalized:
        raise SystemExit(f'nwslid entry {nwslid} has empty field {key}')
    return normalized


def require_float(entry: dict[str, object], nwslid: str, key: str) -> float:
    value = entry.get(key)
    if not isinstance(value, (int, float)):
        raise SystemExit(f'nwslid entry {nwslid} must define numeric field {key}')
    return float(value)


def load_catalog() -> list[tuple[str, NwslidCatalogEntry]]:
    raw = json.loads(CATALOG_PATH.read_text(encoding='utf-8'))
    if not isinstance(raw, dict):
        raise SystemExit('nwslid catalog JSON must be an object keyed by NWSLID')

    entries: dict[str, NwslidCatalogEntry] = {}
    for nwslid_key, entry in raw.items():
        if not isinstance(nwslid_key, str):
            raise SystemExit('nwslid catalog keys must be strings')
        if not isinstance(entry, dict):
            raise SystemExit(f'nwslid entry {nwslid_key} must be an object')

        nwslid = nwslid_key.strip().upper()
        if len(nwslid) != 5 or not nwslid.isalnum():
            raise SystemExit(f'invalid NWSLID key: {nwslid_key!r}')

        normalized: NwslidCatalogEntry = {
            'state_code': require_str(entry, nwslid, 'state_code').upper(),
            'stream_name': require_str(entry, nwslid, 'stream_name'),
            'proximity': require_str(entry, nwslid, 'proximity'),
            'place_name': require_str(entry, nwslid, 'place_name'),
            'latitude': require_float(entry, nwslid, 'latitude'),
            'longitude': require_float(entry, nwslid, 'longitude'),
        }

        if len(normalized['state_code']) < 2 or len(normalized['state_code']) > 3:
            raise SystemExit(
                f"invalid state_code for {nwslid}: {normalized['state_code']!r}"
            )

        previous = entries.get(nwslid)
        if previous and previous != normalized:
            raise SystemExit(
                f'conflicting nwslid entry for {nwslid}: {previous} vs {normalized}'
            )
        entries[nwslid] = normalized

    return sorted(entries.items())


def rust_string(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def rust_float(value: float) -> str:
    formatted = f'{value:.4f}'
    if '.' not in formatted:
        formatted += '.0'
    return formatted


def write_output(catalog: list[tuple[str, NwslidCatalogEntry]]) -> None:
    generated_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace('+00:00', 'Z')
    )

    lines = [
        '// @generated by scripts/generate_nwslid_data.py',
        '// Source file:',
        '// - crates/emwin-parser/data/nwslid.json',
        '// Do not edit manually.',
        '',
        'use super::NwslidEntry;',
        '',
        f'pub const NWSLID_GENERATED_AT_UTC: &str = {rust_string(generated_at)};',
        f'pub const NWSLID_ENTRY_COUNT: usize = {len(catalog)};',
        '',
        'pub static NWSLID_CATALOG: [NwslidEntry; NWSLID_ENTRY_COUNT] = [',
    ]

    for nwslid, entry in catalog:
        lines.extend(
            [
                '    NwslidEntry {',
                f'        nwslid: {rust_string(nwslid)},',
                f"        state_code: {rust_string(entry['state_code'])},",
                f"        stream_name: {rust_string(entry['stream_name'])},",
                f"        proximity: {rust_string(entry['proximity'])},",
                f"        place_name: {rust_string(entry['place_name'])},",
                f"        latitude: {rust_float(entry['latitude'])},",
                f"        longitude: {rust_float(entry['longitude'])},",
                '    },',
            ]
        )

    lines.extend(['];', ''])
    OUTPUT_PATH.write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    write_output(load_catalog())
