// @generated by scripts/generate_product_data.py
// Source files:
// - crates/emwin-parser/data/afos_routing_overrides.json
// Do not edit manually.

#[allow(unused_imports)]
use super::{AfosRoutingOverride, TextProductBodyBehavior, TextProductRouting};
#[allow(unused_imports)]
use crate::body::BodyExtractorId;

#[allow(dead_code)]
pub const AFOS_ROUTING_GENERATED_AT_UTC: &str = "2026-03-12T19:30:58Z";
pub const AFOS_ROUTING_OVERRIDE_COUNT: usize = 0;

pub static AFOS_ROUTING_OVERRIDES: [AfosRoutingOverride; AFOS_ROUTING_OVERRIDE_COUNT] = [];
