// @generated by scripts/generate_product_data.py
// Source file:
// - crates/emwin-parser/data/product_catalog.csv
// Provenance:
// - repo: bradsjm/nwws2mqtt
// - path: docs/weather/Product List.md
// - commit: 9687d59674638ab680aff384ae77f959133ca554
// Do not edit manually.

use super::PilCatalogEntry;

pub const PIL_SOURCE_REPO: &str = "bradsjm/nwws2mqtt";
pub const PIL_SOURCE_PATH: &str = "docs/weather/Product List.md";
pub const PIL_SOURCE_COMMIT: &str = "9687d59674638ab680aff384ae77f959133ca554";
pub const PIL_GENERATED_AT_UTC: &str = "2026-03-06T13:46:28Z";
pub const PIL_ENTRY_COUNT: usize = 422;

pub static PIL_CATALOG: [PilCatalogEntry; PIL_ENTRY_COUNT] = [
    PilCatalogEntry {
        pil: "18A",
        wmo_prefix: "FB",
        title: "18 Hour Report",
    },
    PilCatalogEntry {
        pil: "24A",
        wmo_prefix: "FB",
        title: "24 Hour Report",
    },
    PilCatalogEntry {
        pil: "30L",
        wmo_prefix: "FE",
        title: "Monthly Weather Outlook",
    },
    PilCatalogEntry {
        pil: "5TC",
        wmo_prefix: "AU",
        title: "500 Millibar Type Correlation",
    },
    PilCatalogEntry {
        pil: "ABV",
        wmo_prefix: "UF",
        title: "Rawinsonde Data Above 100 Millibars",
    },
    PilCatalogEntry {
        pil: "ADA",
        wmo_prefix: "NO",
        title: "Alarm/Alert Administrative Message",
    },
    PilCatalogEntry {
        pil: "ADM",
        wmo_prefix: "NO",
        title: "Alert Administrative Message",
    },
    PilCatalogEntry {
        pil: "ADR",
        wmo_prefix: "NO",
        title: "Administrative Message",
    },
    PilCatalogEntry {
        pil: "ADV",
        wmo_prefix: "NW",
        title: "Official Space Weather Advisory",
    },
    PilCatalogEntry {
        pil: "ADW",
        wmo_prefix: "NO",
        title: "Administrative Message for NWWS",
    },
    PilCatalogEntry {
        pil: "ADX",
        wmo_prefix: "NT",
        title: "Administrative Alert Non-Receipt",
    },
    PilCatalogEntry {
        pil: "AFD",
        wmo_prefix: "FX",
        title: "Area Forecast Discussion",
    },
    PilCatalogEntry {
        pil: "AFM",
        wmo_prefix: "FO",
        title: "Area Forecast Matrices",
    },
    PilCatalogEntry {
        pil: "AFP",
        wmo_prefix: "FL",
        title: "Area Forecast Product",
    },
    PilCatalogEntry {
        pil: "AGF",
        wmo_prefix: "FN",
        title: "Agricultural Forecast",
    },
    PilCatalogEntry {
        pil: "AGO",
        wmo_prefix: "SH",
        title: "Agricultural Observations",
    },
    PilCatalogEntry {
        pil: "ALM",
        wmo_prefix: "NW",
        title: "Space Environment Alarm",
    },
    PilCatalogEntry {
        pil: "ALT",
        wmo_prefix: "WO",
        title: "Space Weather Message Alert",
    },
    PilCatalogEntry {
        pil: "APG",
        wmo_prefix: "AE",
        title: "Air Stagnation Guidance Narrative",
    },
    PilCatalogEntry {
        pil: "AQA",
        wmo_prefix: "AE",
        title: "Air Quality Message",
    },
    PilCatalogEntry {
        pil: "AQI",
        wmo_prefix: "AE",
        title: "Air Quality Index Statement",
    },
    PilCatalogEntry {
        pil: "ARP",
        wmo_prefix: "UA",
        title: "AIREPS",
    },
    PilCatalogEntry {
        pil: "ASA",
        wmo_prefix: "AE",
        title: "Air Stagnation Advisory",
    },
    PilCatalogEntry {
        pil: "AVA",
        wmo_prefix: "WO",
        title: "Avalanche Watch",
    },
    PilCatalogEntry {
        pil: "AVM",
        wmo_prefix: "NO",
        title: "Aviation Verification Matrix",
    },
    PilCatalogEntry {
        pil: "AVW",
        wmo_prefix: "WO",
        title: "Avalanche Warning",
    },
    PilCatalogEntry {
        pil: "AWG",
        wmo_prefix: "WO",
        title: "National Attack Warning",
    },
    PilCatalogEntry {
        pil: "AWO",
        wmo_prefix: "NO",
        title: "Area Weather Outlook",
    },
    PilCatalogEntry {
        pil: "AWS",
        wmo_prefix: "AW",
        title: "Area Weather Summary",
    },
    PilCatalogEntry {
        pil: "AWU",
        wmo_prefix: "FL",
        title: "Area Weather Update",
    },
    PilCatalogEntry {
        pil: "AWW",
        wmo_prefix: "WW",
        title: "Aviation Weather Warning",
    },
    PilCatalogEntry {
        pil: "BOY",
        wmo_prefix: "SS",
        title: "Buoy Reports",
    },
    PilCatalogEntry {
        pil: "BRT",
        wmo_prefix: "AX",
        title: "Area Synopsis and Forecast",
    },
    PilCatalogEntry {
        pil: "CAE",
        wmo_prefix: "WO",
        title: "Child Abduction Emergency",
    },
    PilCatalogEntry {
        pil: "CAP",
        wmo_prefix: "XO",
        title: "Alert Messages in CAP XML",
    },
    PilCatalogEntry {
        pil: "CCF",
        wmo_prefix: "FP",
        title: "Coded City Forecast",
    },
    PilCatalogEntry {
        pil: "CDW",
        wmo_prefix: "WO",
        title: "Civil Danger Warning",
    },
    PilCatalogEntry {
        pil: "CEM",
        wmo_prefix: "WO",
        title: "Civil Emergency Message",
    },
    PilCatalogEntry {
        pil: "CF6",
        wmo_prefix: "CX",
        title: "Climate F-6 products",
    },
    PilCatalogEntry {
        pil: "CFP",
        wmo_prefix: "FA",
        title: "Convective Forecast Product",
    },
    PilCatalogEntry {
        pil: "CFW",
        wmo_prefix: "WH",
        title: "Coastal/Lakeshore Hazard Messages",
    },
    PilCatalogEntry {
        pil: "CGR",
        wmo_prefix: "SX",
        title: "Coast Guard Surface Report",
    },
    PilCatalogEntry {
        pil: "CHG",
        wmo_prefix: "WT",
        title: "Computer Hurricane Guidance",
    },
    PilCatalogEntry {
        pil: "CLA",
        wmo_prefix: "CX",
        title: "Climate Report Annual",
    },
    PilCatalogEntry {
        pil: "CLI",
        wmo_prefix: "CD",
        title: "Climate Report Daily",
    },
    PilCatalogEntry {
        pil: "CLM",
        wmo_prefix: "CX",
        title: "Climate Report Monthly",
    },
    PilCatalogEntry {
        pil: "CLS",
        wmo_prefix: "CX",
        title: "Climate Report Seasonal",
    },
    PilCatalogEntry {
        pil: "CMM",
        wmo_prefix: "CS",
        title: "Coded Climatological Monthly Means",
    },
    PilCatalogEntry {
        pil: "COD",
        wmo_prefix: "FX",
        title: "Coded Analysis and Forecasts",
    },
    PilCatalogEntry {
        pil: "CSC",
        wmo_prefix: "FP",
        title: "Canadian Selected Cities Forecast",
    },
    PilCatalogEntry {
        pil: "CUR",
        wmo_prefix: "FX",
        title: "Current Space Weather Indices",
    },
    PilCatalogEntry {
        pil: "CWA",
        wmo_prefix: "WL",
        title: "Center Weather Advisory",
    },
    PilCatalogEntry {
        pil: "CWD",
        wmo_prefix: "NZ",
        title: "Discussion for Coastal Waters Forecast",
    },
    PilCatalogEntry {
        pil: "CWF",
        wmo_prefix: "FZ",
        title: "Coastal Waters Forecast",
    },
    PilCatalogEntry {
        pil: "CWS",
        wmo_prefix: "WO",
        title: "Center Weather Statement",
    },
    PilCatalogEntry {
        pil: "DAA",
        wmo_prefix: "SD",
        title: "170 QPE One Hour Digital Accumulation",
    },
    PilCatalogEntry {
        pil: "DAY",
        wmo_prefix: "FX",
        title: "Daily Space Weather Summary and Forcast",
    },
    PilCatalogEntry {
        pil: "DGT",
        wmo_prefix: "AX",
        title: "Drought Information",
    },
    PilCatalogEntry {
        pil: "DHR",
        wmo_prefix: "SD",
        title: "Digital Hybrid Reflectivity",
    },
    PilCatalogEntry {
        pil: "DMO",
        wmo_prefix: "WO",
        title: "Practice/Demo Warning",
    },
    PilCatalogEntry {
        pil: "DOD",
        wmo_prefix: "SD",
        title: "174 QPE-PPS One Hour Accumulation Difference",
    },
    PilCatalogEntry {
        pil: "DPA",
        wmo_prefix: "SD",
        title: "Radar Hourly Digital Precipitation",
    },
    PilCatalogEntry {
        pil: "DPR",
        wmo_prefix: "SD",
        title: "176 QPE Instanteaneous Precipitation Rate",
    },
    PilCatalogEntry {
        pil: "DSA",
        wmo_prefix: "AC",
        title: "Unnumbered Depression",
    },
    PilCatalogEntry {
        pil: "DSM",
        wmo_prefix: "CX",
        title: "Asos Daily Summary",
    },
    PilCatalogEntry {
        pil: "DSP",
        wmo_prefix: "SD",
        title: "Adigital Storm Total Precipitation Nexrad",
    },
    PilCatalogEntry {
        pil: "DST",
        wmo_prefix: "CX",
        title: "ASOS Daily Summary",
    },
    PilCatalogEntry {
        pil: "DSW",
        wmo_prefix: "WW",
        title: "Dust Storm Warning",
    },
    PilCatalogEntry {
        pil: "DU3",
        wmo_prefix: "SD",
        title: "173 QPE User Selectable 3 Hour Accumulation",
    },
    PilCatalogEntry {
        pil: "DU6",
        wmo_prefix: "SD",
        title: "173 QPE User Selectable 24 Hour Accumulation",
    },
    PilCatalogEntry {
        pil: "EAN",
        wmo_prefix: "WO",
        title: "Presidential Alert",
    },
    PilCatalogEntry {
        pil: "EET",
        wmo_prefix: "SD",
        title: "135 Radar Enhanced Echo Tops",
    },
    PilCatalogEntry {
        pil: "EFP",
        wmo_prefix: "FE",
        title: "3 TO 5 Day Extended Forecast",
    },
    PilCatalogEntry {
        pil: "EOL",
        wmo_prefix: "FE",
        title: "Average 6 TO 10 Day Weather Outlook",
    },
    PilCatalogEntry {
        pil: "EON",
        wmo_prefix: "FE",
        title: "Average 6 TO 10 Day Weather Outlook",
    },
    PilCatalogEntry {
        pil: "EQI",
        wmo_prefix: "SE",
        title: "Earthquake Information Bulletin",
    },
    PilCatalogEntry {
        pil: "EQR",
        wmo_prefix: "SE",
        title: "Earthquake Report",
    },
    PilCatalogEntry {
        pil: "EQW",
        wmo_prefix: "WO",
        title: "Earthquake Warning",
    },
    PilCatalogEntry {
        pil: "ESF",
        wmo_prefix: "FG",
        title: "Flood Potential Outlook",
    },
    PilCatalogEntry {
        pil: "ESG",
        wmo_prefix: "FG",
        title: "Extended Streamflow Guidance",
    },
    PilCatalogEntry {
        pil: "ESP",
        wmo_prefix: "FG",
        title: "Extended Streamflow Prediction",
    },
    PilCatalogEntry {
        pil: "ESS",
        wmo_prefix: "FG",
        title: "Water Supply Outlook",
    },
    PilCatalogEntry {
        pil: "EVI",
        wmo_prefix: "WO",
        title: "Evacuation Immediate",
    },
    PilCatalogEntry {
        pil: "EWW",
        wmo_prefix: "WF",
        title: "Extreme Wind Warning",
    },
    PilCatalogEntry {
        pil: "FA0",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Pacific)",
    },
    PilCatalogEntry {
        pil: "FA1",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Northeast U.S.)",
    },
    PilCatalogEntry {
        pil: "FA2",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Southeast U.S.)",
    },
    PilCatalogEntry {
        pil: "FA3",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (North Cent U.S.)",
    },
    PilCatalogEntry {
        pil: "FA4",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (South Cent U.S.)",
    },
    PilCatalogEntry {
        pil: "FA5",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (U.S. Rocky Mts.)",
    },
    PilCatalogEntry {
        pil: "FA6",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (U.S. West Coast)",
    },
    PilCatalogEntry {
        pil: "FA7",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Juneau)",
    },
    PilCatalogEntry {
        pil: "FA8",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Anchorage)",
    },
    PilCatalogEntry {
        pil: "FA9",
        wmo_prefix: "FA",
        title: "Aviation Area Forecast (Fairbanks)",
    },
    PilCatalogEntry {
        pil: "FAK",
        wmo_prefix: "FA",
        title: "Alaskan Model Output Statistics Forecast",
    },
    PilCatalogEntry {
        pil: "FAN",
        wmo_prefix: "FE",
        title: "AVN Based MOS Guidance",
    },
    PilCatalogEntry {
        pil: "FAV",
        wmo_prefix: "FA",
        title: "Aviation Area forecast",
    },
    PilCatalogEntry {
        pil: "FBP",
        wmo_prefix: "FO",
        title: "AK FOUS 24, 36, and 24 Boundary",
    },
    PilCatalogEntry {
        pil: "FD0",
        wmo_prefix: "FB",
        title: "24 Hr FD Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FD1",
        wmo_prefix: "FB",
        title: "6 Hour Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FD2",
        wmo_prefix: "FB",
        title: "12 Hour Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FD3",
        wmo_prefix: "FB",
        title: "24 Hour Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FD8",
        wmo_prefix: "FB",
        title: "24 Hour Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FD9",
        wmo_prefix: "FB",
        title: "6 Hour Winds Aloft Forecast",
    },
    PilCatalogEntry {
        pil: "FDI",
        wmo_prefix: "FN",
        title: "Fire Danger Indices",
    },
    PilCatalogEntry {
        pil: "FFA",
        wmo_prefix: "WG",
        title: "Flash Flood Watch",
    },
    PilCatalogEntry {
        pil: "FFG",
        wmo_prefix: "FO",
        title: "Flash Flood Guidance",
    },
    PilCatalogEntry {
        pil: "FFH",
        wmo_prefix: "FO",
        title: "Headwater Guidance",
    },
    PilCatalogEntry {
        pil: "FFS",
        wmo_prefix: "WG",
        title: "Flash Flood Statement",
    },
    PilCatalogEntry {
        pil: "FFW",
        wmo_prefix: "WG",
        title: "Flash Flood Warning",
    },
    PilCatalogEntry {
        pil: "FLN",
        wmo_prefix: "FG",
        title: "National Flood Summary",
    },
    PilCatalogEntry {
        pil: "FLS",
        wmo_prefix: "WG",
        title: "Flood Statement",
    },
    PilCatalogEntry {
        pil: "FLW",
        wmo_prefix: "WG",
        title: "Flood Warning",
    },
    PilCatalogEntry {
        pil: "FMR",
        wmo_prefix: "FE",
        title: "Forecast Medium Range Guidance",
    },
    PilCatalogEntry {
        pil: "FOF",
        wmo_prefix: "FD",
        title: "Upper Wind Fallout Forecast",
    },
    PilCatalogEntry {
        pil: "FOH",
        wmo_prefix: "FO",
        title: "ETA FOUS Freezing and Relative Humidity",
    },
    PilCatalogEntry {
        pil: "FRH",
        wmo_prefix: "FO",
        title: "FOUS Relative Humidity/Temperature Guidance",
    },
    PilCatalogEntry {
        pil: "FRW",
        wmo_prefix: "WO",
        title: "Fire Warning",
    },
    PilCatalogEntry {
        pil: "FSH",
        wmo_prefix: "NO",
        title: "National Marine Fisheries Message",
    },
    PilCatalogEntry {
        pil: "FTJ",
        wmo_prefix: "FO",
        title: "FOUS Trajectory Forecast",
    },
    PilCatalogEntry {
        pil: "FTM",
        wmo_prefix: "NO",
        title: "WSR-88D Radar Status Notification",
    },
    PilCatalogEntry {
        pil: "FTP",
        wmo_prefix: "FO",
        title: "FOUS Prog Max/Min Temp/Pop Guidance",
    },
    PilCatalogEntry {
        pil: "FWA",
        wmo_prefix: "NO",
        title: "Fire Weather Administrative Message",
    },
    PilCatalogEntry {
        pil: "FWC",
        wmo_prefix: "FO",
        title: "NGM Mos Guidance",
    },
    PilCatalogEntry {
        pil: "FWD",
        wmo_prefix: "FN",
        title: "Fire Weather Outlook Discussion",
    },
    PilCatalogEntry {
        pil: "FWE",
        wmo_prefix: "FE",
        title: "Extended Fire Weather Outlook",
    },
    PilCatalogEntry {
        pil: "FWF",
        wmo_prefix: "FN",
        title: "Routine Fire WX Forecasts",
    },
    PilCatalogEntry {
        pil: "FWL",
        wmo_prefix: "FN",
        title: "Land Management Forecasts",
    },
    PilCatalogEntry {
        pil: "FWM",
        wmo_prefix: "FN",
        title: "Miscellaneous Fire Weather Product",
    },
    PilCatalogEntry {
        pil: "FWN",
        wmo_prefix: "SH",
        title: "Fire Weather Notification",
    },
    PilCatalogEntry {
        pil: "FWO",
        wmo_prefix: "SH",
        title: "Fire Weather Observation",
    },
    PilCatalogEntry {
        pil: "FWS",
        wmo_prefix: "FN",
        title: "Suppression Forecast",
    },
    PilCatalogEntry {
        pil: "FZL",
        wmo_prefix: "UX",
        title: "Freezing Level Data",
    },
    PilCatalogEntry {
        pil: "GLF",
        wmo_prefix: "FZ",
        title: "Great Lakes Forecast",
    },
    PilCatalogEntry {
        pil: "GLO",
        wmo_prefix: "FZ",
        title: "Great Lakes Storm Outlook",
    },
    PilCatalogEntry {
        pil: "GLS",
        wmo_prefix: "WW",
        title: "Great Lakes Storm Summary",
    },
    PilCatalogEntry {
        pil: "GSM",
        wmo_prefix: "NX",
        title: "General Status Message",
    },
    PilCatalogEntry {
        pil: "HCM",
        wmo_prefix: "NG",
        title: "Hydrometeorlogical Coordination Message",
    },
    PilCatalogEntry {
        pil: "HD1",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD2",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD3",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD4",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD5",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD6",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD7",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD8",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HD9",
        wmo_prefix: "FP",
        title: "RFC Derived QPF Data Product",
    },
    PilCatalogEntry {
        pil: "HDP",
        wmo_prefix: "AG",
        title: "WSR-88D Hourly Digital Precipitation",
    },
    PilCatalogEntry {
        pil: "HHC",
        wmo_prefix: "SD",
        title: "177 Hybrid Scan Hydrometeor Classification",
    },
    PilCatalogEntry {
        pil: "HLS",
        wmo_prefix: "WT",
        title: "Hurricane Local Statement",
    },
    PilCatalogEntry {
        pil: "HMD",
        wmo_prefix: "AG",
        title: "Hydrometeorological Discussion",
    },
    PilCatalogEntry {
        pil: "HML",
        wmo_prefix: "FD",
        title: "Hyrdo Obs/Forecasts XML",
    },
    PilCatalogEntry {
        pil: "HMW",
        wmo_prefix: "WO",
        title: "Hazardous Materials Warning",
    },
    PilCatalogEntry {
        pil: "HP1",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP2",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP3",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP4",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP5",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP6",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP7",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP8",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HP9",
        wmo_prefix: "FP",
        title: "RFC QPF Verification Product",
    },
    PilCatalogEntry {
        pil: "HRR",
        wmo_prefix: "NZ",
        title: "Hourly Weather Roundup",
    },
    PilCatalogEntry {
        pil: "HSF",
        wmo_prefix: "FZ",
        title: "High Seas Forecast",
    },
    PilCatalogEntry {
        pil: "HWO",
        wmo_prefix: "FL",
        title: "Hazardous Weather Outlook",
    },
    PilCatalogEntry {
        pil: "HYD",
        wmo_prefix: "SX",
        title: "Rainfall Reports",
    },
    PilCatalogEntry {
        pil: "ICE",
        wmo_prefix: "FZ",
        title: "Ice Forecast",
    },
    PilCatalogEntry {
        pil: "ICO",
        wmo_prefix: "FZ",
        title: "Ice Outlook",
    },
    PilCatalogEntry {
        pil: "INI",
        wmo_prefix: "NO",
        title: "Administration",
    },
    PilCatalogEntry {
        pil: "IOB",
        wmo_prefix: "SV",
        title: "Ice Observation",
    },
    PilCatalogEntry {
        pil: "IRM",
        wmo_prefix: "SD",
        title: "Interim Radar Message",
    },
    PilCatalogEntry {
        pil: "KPA",
        wmo_prefix: "NT",
        title: "Keep Alive Message",
    },
    PilCatalogEntry {
        pil: "LAE",
        wmo_prefix: "WO",
        title: "Local Area Emergency",
    },
    PilCatalogEntry {
        pil: "LAW",
        wmo_prefix: "SM",
        title: "Great Lakes Weather Observation",
    },
    PilCatalogEntry {
        pil: "LCO",
        wmo_prefix: "SX",
        title: "Local Cooperative Observation",
    },
    PilCatalogEntry {
        pil: "LEW",
        wmo_prefix: "WO",
        title: "Law Enforcement Warning",
    },
    PilCatalogEntry {
        pil: "LFP",
        wmo_prefix: "FL",
        title: "Local Forecast",
    },
    PilCatalogEntry {
        pil: "LLS",
        wmo_prefix: "UX",
        title: "Low-Level Sounding",
    },
    PilCatalogEntry {
        pil: "LSH",
        wmo_prefix: "WH",
        title: "Lakeshore Warning or Statement",
    },
    PilCatalogEntry {
        pil: "LSR",
        wmo_prefix: "NW",
        title: "Local Storm Report",
    },
    PilCatalogEntry {
        pil: "LTG",
        wmo_prefix: "SF",
        title: "Lightning Data",
    },
    PilCatalogEntry {
        pil: "MAN",
        wmo_prefix: "US",
        title: "Rawinsonde Observation Mandatory Levels",
    },
    PilCatalogEntry {
        pil: "MAP",
        wmo_prefix: "AG",
        title: "Mean Areal Precipitation",
    },
    PilCatalogEntry {
        pil: "MAV",
        wmo_prefix: "FO",
        title: "GFS Based MOS Guidance",
    },
    PilCatalogEntry {
        pil: "MAW",
        wmo_prefix: "FO",
        title: "MOS Avaiation-based Guidance",
    },
    PilCatalogEntry {
        pil: "MEF",
        wmo_prefix: "NZ",
        title: "AFOS Forecast Verification Matrix",
    },
    PilCatalogEntry {
        pil: "MET",
        wmo_prefix: "FO",
        title: "ETA Based MOS Guidance",
    },
    PilCatalogEntry {
        pil: "MEX",
        wmo_prefix: "FE",
        title: "GFX Extended Based MOS Guidance",
    },
    PilCatalogEntry {
        pil: "MIM",
        wmo_prefix: "AG",
        title: "Marine Interpretation Message",
    },
    PilCatalogEntry {
        pil: "MIS",
        wmo_prefix: "AX",
        title: "Miscellaneous Local Product",
    },
    PilCatalogEntry {
        pil: "MON",
        wmo_prefix: "NT",
        title: "Test Message",
    },
    PilCatalogEntry {
        pil: "MRM",
        wmo_prefix: "NO",
        title: "Missing Radar Message",
    },
    PilCatalogEntry {
        pil: "MRP",
        wmo_prefix: "AG",
        title: "Techniques Development Laboratory Marine",
    },
    PilCatalogEntry {
        pil: "MSM",
        wmo_prefix: "CS",
        title: "ASOS Monthly Summary Message",
    },
    PilCatalogEntry {
        pil: "MST",
        wmo_prefix: "CS",
        title: "ASOS Monthly Summary Message Test",
    },
    PilCatalogEntry {
        pil: "MTR",
        wmo_prefix: "SA",
        title: "METAR Formatted Surface Weather Observation",
    },
    PilCatalogEntry {
        pil: "MTT",
        wmo_prefix: "SX",
        title: "METAR Test Message",
    },
    PilCatalogEntry {
        pil: "MWS",
        wmo_prefix: "FZ",
        title: "Marine Weather Statement",
    },
    PilCatalogEntry {
        pil: "MWW",
        wmo_prefix: "WH",
        title: "Marine Weather Message",
    },
    PilCatalogEntry {
        pil: "N0V",
        wmo_prefix: "SD",
        title: "RADAR .5 VELOCITY .54NM RES 16 LEVELS ID 27/V",
    },
    PilCatalogEntry {
        pil: "N0W",
        wmo_prefix: "SD",
        title: "RADAR BASE RADIAL VELOCITY 25/V",
    },
    PilCatalogEntry {
        pil: "NC1",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL (CFC) - SEGMENT 1",
    },
    PilCatalogEntry {
        pil: "NC2",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL (CFC) - SEGMENT 2",
    },
    PilCatalogEntry {
        pil: "NC3",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL (CFC) - SEGMENT 3",
    },
    PilCatalogEntry {
        pil: "NC4",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL (CFC) - SEGMENT 4",
    },
    PilCatalogEntry {
        pil: "NC5",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL (CFC) - SEGMENT 5",
    },
    PilCatalogEntry {
        pil: "NCF",
        wmo_prefix: "SD",
        title: "CLUTTER FILTER CONTROL",
    },
    PilCatalogEntry {
        pil: "NET",
        wmo_prefix: "SD",
        title: "RADAR ECHO TOPS ID 41/ET",
    },
    PilCatalogEntry {
        pil: "NHI",
        wmo_prefix: "SD",
        title: "HAIL INDEX 59/HI",
    },
    PilCatalogEntry {
        pil: "NIC",
        wmo_prefix: "WO",
        title: "National Information Center",
    },
    PilCatalogEntry {
        pil: "NME",
        wmo_prefix: "SD",
        title: "MESOCYCLONE 60/M",
    },
    PilCatalogEntry {
        pil: "NMN",
        wmo_prefix: "WO",
        title: "Network Message Notification",
    },
    PilCatalogEntry {
        pil: "NOW",
        wmo_prefix: "FP",
        title: "Short Term Forecast",
    },
    PilCatalogEntry {
        pil: "NPT",
        wmo_prefix: "WO",
        title: "National Periodic Test",
    },
    PilCatalogEntry {
        pil: "NPW",
        wmo_prefix: "WW",
        title: "Non-Precipitation Message",
    },
    PilCatalogEntry {
        pil: "NSH",
        wmo_prefix: "FZ",
        title: "Nearshore Marine Forecast / Surf Forecast",
    },
    PilCatalogEntry {
        pil: "NSP",
        wmo_prefix: "SD",
        title: "Base Spectrum Width 32NM .13NM X 1 Deg",
    },
    PilCatalogEntry {
        pil: "NSS",
        wmo_prefix: "SD",
        title: "Storm Structure",
    },
    PilCatalogEntry {
        pil: "NST",
        wmo_prefix: "SD",
        title: "Storm Tracking Information",
    },
    PilCatalogEntry {
        pil: "NSW",
        wmo_prefix: "SD",
        title: "Base Spectrum Width 124NM .54NM X 1 Deg",
    },
    PilCatalogEntry {
        pil: "NTP",
        wmo_prefix: "SD",
        title: "Radar Storm Total Precipitation Accumulation",
    },
    PilCatalogEntry {
        pil: "NTV",
        wmo_prefix: "SD",
        title: "Tornado Vortex Signature",
    },
    PilCatalogEntry {
        pil: "NUP",
        wmo_prefix: "SD",
        title: "Radar User Select Precipitation Accumulation",
    },
    PilCatalogEntry {
        pil: "NUW",
        wmo_prefix: "WO",
        title: "Nuclear Power Plant Warning",
    },
    PilCatalogEntry {
        pil: "NVL",
        wmo_prefix: "SD",
        title: "Radar Vertically Integrated Liquid",
    },
    PilCatalogEntry {
        pil: "NVW",
        wmo_prefix: "SD",
        title: "Radar Velocity Azimuth Display Wind Profile",
    },
    PilCatalogEntry {
        pil: "NWP",
        wmo_prefix: "SD",
        title: "Severe Weather Probability",
    },
    PilCatalogEntry {
        pil: "NWR",
        wmo_prefix: "NZ",
        title: "NOAA Weather radio Forecast",
    },
    PilCatalogEntry {
        pil: "OAV",
        wmo_prefix: "NO",
        title: "Other Aviation Products",
    },
    PilCatalogEntry {
        pil: "OCD",
        wmo_prefix: "AG",
        title: "Oceanographic Data",
    },
    PilCatalogEntry {
        pil: "OEP",
        wmo_prefix: "NZ",
        title: "Operational Evolution Plan",
    },
    PilCatalogEntry {
        pil: "OFA",
        wmo_prefix: "FA",
        title: "Offshore Aviation Area Forecast",
    },
    PilCatalogEntry {
        pil: "OFF",
        wmo_prefix: "FZ",
        title: "Offshore Forecast",
    },
    PilCatalogEntry {
        pil: "OMR",
        wmo_prefix: "SX",
        title: "Other Marine Products",
    },
    PilCatalogEntry {
        pil: "OPU",
        wmo_prefix: "FP",
        title: "Other Public Products",
    },
    PilCatalogEntry {
        pil: "OSB",
        wmo_prefix: "AG",
        title: "Oceanographic Spectral Bulletin",
    },
    PilCatalogEntry {
        pil: "OSO",
        wmo_prefix: "SX",
        title: "Other Surface Observations",
    },
    PilCatalogEntry {
        pil: "OSW",
        wmo_prefix: "AG",
        title: "Ocean Surface Winds",
    },
    PilCatalogEntry {
        pil: "OUA",
        wmo_prefix: "UX",
        title: "Other Upper Air Data",
    },
    PilCatalogEntry {
        pil: "PAR",
        wmo_prefix: "NO",
        title: "Performance Accomplishment Report",
    },
    PilCatalogEntry {
        pil: "PBF",
        wmo_prefix: "FN",
        title: "Prescribed Burn Forecast",
    },
    PilCatalogEntry {
        pil: "PFM",
        wmo_prefix: "FO",
        title: "Point Forecast Matrices",
    },
    PilCatalogEntry {
        pil: "PFW",
        wmo_prefix: "FO",
        title: "Point Fire Weather Forecast Matrices",
    },
    PilCatalogEntry {
        pil: "PIB",
        wmo_prefix: "UP",
        title: "Pibal Observation",
    },
    PilCatalogEntry {
        pil: "PIR",
        wmo_prefix: "UA",
        title: "Pilot Report",
    },
    PilCatalogEntry {
        pil: "PLS",
        wmo_prefix: "SX",
        title: "Plain Language Ship Report",
    },
    PilCatalogEntry {
        pil: "PMD",
        wmo_prefix: "FX",
        title: "Prognostic Meteorological Discussion",
    },
    PilCatalogEntry {
        pil: "PNS",
        wmo_prefix: "NO",
        title: "Public Information Statement",
    },
    PilCatalogEntry {
        pil: "POE",
        wmo_prefix: "FX",
        title: "Probabiilty of Exceed",
    },
    PilCatalogEntry {
        pil: "PRB",
        wmo_prefix: "FM",
        title: "Days 3--7 Heat Index Forecast Tables",
    },
    PilCatalogEntry {
        pil: "PRC",
        wmo_prefix: "UA",
        title: "State Pilot Report Collective",
    },
    PilCatalogEntry {
        pil: "PSH",
        wmo_prefix: "AC",
        title: "Post Storm Hurricane Report",
    },
    PilCatalogEntry {
        pil: "PSM",
        wmo_prefix: "FX",
        title: "Pronostic Snow Melt",
    },
    PilCatalogEntry {
        pil: "PVM",
        wmo_prefix: "FX",
        title: "Public Verification Matrix",
    },
    PilCatalogEntry {
        pil: "PWO",
        wmo_prefix: "WW",
        title: "Public Severe Weather Alert",
    },
    PilCatalogEntry {
        pil: "QCD",
        wmo_prefix: "NT",
        title: "ASOS Daily Quality Control Message",
    },
    PilCatalogEntry {
        pil: "QCH",
        wmo_prefix: "NT",
        title: "ASOS Hourly Quality Control Message",
    },
    PilCatalogEntry {
        pil: "QCM",
        wmo_prefix: "NT",
        title: "ASOS Monthly Quality Control Message",
    },
    PilCatalogEntry {
        pil: "QCW",
        wmo_prefix: "NT",
        title: "ASOS Weekly Quality Control Message",
    },
    PilCatalogEntry {
        pil: "QPF",
        wmo_prefix: "FS",
        title: "Quantitative Precipitation Forecast",
    },
    PilCatalogEntry {
        pil: "QPS",
        wmo_prefix: "FS",
        title: "Quantitative Precipitation Statement",
    },
    PilCatalogEntry {
        pil: "RBG",
        wmo_prefix: "PX",
        title: "Red Book Graphic",
    },
    PilCatalogEntry {
        pil: "RCM",
        wmo_prefix: "SD",
        title: "WSR-88D Radar Coded Message",
    },
    PilCatalogEntry {
        pil: "RDF",
        wmo_prefix: "FO",
        title: "Revised Digital Forecast",
    },
    PilCatalogEntry {
        pil: "RDG",
        wmo_prefix: "FO",
        title: "Revised Digital Guidance",
    },
    PilCatalogEntry {
        pil: "REC",
        wmo_prefix: "SX",
        title: "Recreational Report",
    },
    PilCatalogEntry {
        pil: "RER",
        wmo_prefix: "SX",
        title: "Record Event Report",
    },
    PilCatalogEntry {
        pil: "RFD",
        wmo_prefix: "FN",
        title: "Rangeland Fire Danger Forecast",
    },
    PilCatalogEntry {
        pil: "RFR",
        wmo_prefix: "FR",
        title: "Route Forecast",
    },
    PilCatalogEntry {
        pil: "RFW",
        wmo_prefix: "WW",
        title: "Red Flag Warning",
    },
    PilCatalogEntry {
        pil: "RHW",
        wmo_prefix: "WO",
        title: "Radiological Hazard Warning",
    },
    PilCatalogEntry {
        pil: "RMT",
        wmo_prefix: "WO",
        title: "Required Monthly Test",
    },
    PilCatalogEntry {
        pil: "RR1",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 1",
    },
    PilCatalogEntry {
        pil: "RR2",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 2",
    },
    PilCatalogEntry {
        pil: "RR3",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 3",
    },
    PilCatalogEntry {
        pil: "RR4",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 4",
    },
    PilCatalogEntry {
        pil: "RR5",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 5",
    },
    PilCatalogEntry {
        pil: "RR6",
        wmo_prefix: "SR",
        title: "ASOS Shef Precip Criteria Message",
    },
    PilCatalogEntry {
        pil: "RR7",
        wmo_prefix: "SR",
        title: "ASOS Shef Hourly Routine Message",
    },
    PilCatalogEntry {
        pil: "RR8",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 8",
    },
    PilCatalogEntry {
        pil: "RR9",
        wmo_prefix: "SR",
        title: "Hydrology Meteorology Data Report Part 9",
    },
    PilCatalogEntry {
        pil: "RRA",
        wmo_prefix: "SR",
        title: "Automated Hydrologic Observation STA Report",
    },
    PilCatalogEntry {
        pil: "RRC",
        wmo_prefix: "SR",
        title: "SCS Manual Snow Course Data",
    },
    PilCatalogEntry {
        pil: "RRM",
        wmo_prefix: "SR",
        title: "Miscellaneous Hydrologic Data",
    },
    PilCatalogEntry {
        pil: "RRS",
        wmo_prefix: "SR",
        title: "Special Automated Hydromet Data Report",
    },
    PilCatalogEntry {
        pil: "RRX",
        wmo_prefix: "SR",
        title: "ASOS Shef Precipitation Criteria Test Message",
    },
    PilCatalogEntry {
        pil: "RRY",
        wmo_prefix: "SR",
        title: "ASOS Shef Hourly Routine Test Message",
    },
    PilCatalogEntry {
        pil: "RSD",
        wmo_prefix: "CX",
        title: "Daily Snotel Data",
    },
    PilCatalogEntry {
        pil: "RSL",
        wmo_prefix: "SD",
        title: "WSR-88D Rpg System Status Logs",
    },
    PilCatalogEntry {
        pil: "RSM",
        wmo_prefix: "CS",
        title: "Monthly Snotel Data",
    },
    PilCatalogEntry {
        pil: "RTP",
        wmo_prefix: "AS",
        title: "Max/Min Temperature and Precipitation Table",
    },
    PilCatalogEntry {
        pil: "RVA",
        wmo_prefix: "SR",
        title: "River Summary",
    },
    PilCatalogEntry {
        pil: "RVD",
        wmo_prefix: "FG",
        title: "Daily River Forecast",
    },
    PilCatalogEntry {
        pil: "RVF",
        wmo_prefix: "FG",
        title: "River Forecast",
    },
    PilCatalogEntry {
        pil: "RVG",
        wmo_prefix: "NZ",
        title: "Hydrologic Statement",
    },
    PilCatalogEntry {
        pil: "RVI",
        wmo_prefix: "FI",
        title: "River Ice Statement",
    },
    PilCatalogEntry {
        pil: "RVK",
        wmo_prefix: "NZ",
        title: "Hydrologic Statement",
    },
    PilCatalogEntry {
        pil: "RVM",
        wmo_prefix: "SR",
        title: "Miscellaneous River Product",
    },
    PilCatalogEntry {
        pil: "RVR",
        wmo_prefix: "FG",
        title: "River Recreation Statement",
    },
    PilCatalogEntry {
        pil: "RVS",
        wmo_prefix: "FG",
        title: "River Statement",
    },
    PilCatalogEntry {
        pil: "RWO",
        wmo_prefix: "SD",
        title: "Radar Superob",
    },
    PilCatalogEntry {
        pil: "RWR",
        wmo_prefix: "AS",
        title: "Weather Roundup",
    },
    PilCatalogEntry {
        pil: "RWS",
        wmo_prefix: "AW",
        title: "Weather Summary",
    },
    PilCatalogEntry {
        pil: "RWT",
        wmo_prefix: "WO",
        title: "Required Weekly Test",
    },
    PilCatalogEntry {
        pil: "RZF",
        wmo_prefix: "FP",
        title: "Regional Zone Forecast",
    },
    PilCatalogEntry {
        pil: "SAA",
        wmo_prefix: "XX",
        title: "Space Environment Alert Advisory",
    },
    PilCatalogEntry {
        pil: "SAB",
        wmo_prefix: "WW",
        title: "Snow Avalanche Bulletin",
    },
    PilCatalogEntry {
        pil: "SAD",
        wmo_prefix: "AW",
        title: "Daily Surface Aviation Weather Summary",
    },
    PilCatalogEntry {
        pil: "SAG",
        wmo_prefix: "FW",
        title: "Snow Avalanche Guidance",
    },
    PilCatalogEntry {
        pil: "SAM",
        wmo_prefix: "AW",
        title: "Montly Surface Avaiation Weather Summary",
    },
    PilCatalogEntry {
        pil: "SAW",
        wmo_prefix: "WW",
        title: "Prelim Notice of Watch & Cancellation MSG",
    },
    PilCatalogEntry {
        pil: "SCC",
        wmo_prefix: "AC",
        title: "Storm Summary",
    },
    PilCatalogEntry {
        pil: "SCD",
        wmo_prefix: "CX",
        title: "Supplementary Climatological Data (ASOS)",
    },
    PilCatalogEntry {
        pil: "SCN",
        wmo_prefix: "SX",
        title: "Soil Climate Analysis Network Data",
    },
    PilCatalogEntry {
        pil: "SCP",
        wmo_prefix: "TC",
        title: "Satellite Cloud Product",
    },
    PilCatalogEntry {
        pil: "SCS",
        wmo_prefix: "FP",
        title: "Selected Cities Summary",
    },
    PilCatalogEntry {
        pil: "SCV",
        wmo_prefix: "SR",
        title: "Satellite Areal Extent of Snow Cover",
    },
    PilCatalogEntry {
        pil: "SDO",
        wmo_prefix: "SX",
        title: "Supplementary Data Observations (ASOS)",
    },
    PilCatalogEntry {
        pil: "SDS",
        wmo_prefix: "FU",
        title: "Special Dispersion Statement",
    },
    PilCatalogEntry {
        pil: "SES",
        wmo_prefix: "XX",
        title: "Space Enviornment Summary",
    },
    PilCatalogEntry {
        pil: "SEV",
        wmo_prefix: "WW",
        title: "SPC Watch Point Information Message",
    },
    PilCatalogEntry {
        pil: "SFD",
        wmo_prefix: "FX",
        title: "State Forecast Discussion",
    },
    PilCatalogEntry {
        pil: "SFP",
        wmo_prefix: "FP",
        title: "State Forecast",
    },
    PilCatalogEntry {
        pil: "SFT",
        wmo_prefix: "FP",
        title: "Tabular State Forecast",
    },
    PilCatalogEntry {
        pil: "SGL",
        wmo_prefix: "UM",
        title: "Rawinsonde Observation Significant Levels",
    },
    PilCatalogEntry {
        pil: "SGW",
        wmo_prefix: "FA",
        title: "Plain Language Significant Weather Forecast",
    },
    PilCatalogEntry {
        pil: "SIG",
        wmo_prefix: "WS",
        title: "International Sigmet/Convective Sigmet",
    },
    PilCatalogEntry {
        pil: "SIM",
        wmo_prefix: "AT",
        title: "Satellite Interpretation Message",
    },
    PilCatalogEntry {
        pil: "SLS",
        wmo_prefix: "WW",
        title: "Severe Local Storm Watch and Areal Outline",
    },
    PilCatalogEntry {
        pil: "SMA",
        wmo_prefix: "WW",
        title: "Marine Subtropical Storm Advistory",
    },
    PilCatalogEntry {
        pil: "SMF",
        wmo_prefix: "FN",
        title: "Smoke Management Weather Forecast",
    },
    PilCatalogEntry {
        pil: "SMW",
        wmo_prefix: "WH",
        title: "Special Marine Warning",
    },
    PilCatalogEntry {
        pil: "SPE",
        wmo_prefix: "TX",
        title: "Satellite Precipitation Estimates",
    },
    PilCatalogEntry {
        pil: "SPF",
        wmo_prefix: "WT",
        title: "Storm Strike Probability Bulletin",
    },
    PilCatalogEntry {
        pil: "SPS",
        wmo_prefix: "WW",
        title: "Special Weather Statement",
    },
    PilCatalogEntry {
        pil: "SPW",
        wmo_prefix: "WO",
        title: "Shelter in Place Warning",
    },
    PilCatalogEntry {
        pil: "SQW",
        wmo_prefix: "WW",
        title: "Snow Squall Warning",
    },
    PilCatalogEntry {
        pil: "SRF",
        wmo_prefix: "FZ",
        title: "Surf Forecast",
    },
    PilCatalogEntry {
        pil: "SSA",
        wmo_prefix: "XX",
        title: "Space Environment Summary Advisory",
    },
    PilCatalogEntry {
        pil: "STA",
        wmo_prefix: "NW",
        title: "SPC Tornado and Severe Thunderstorm Reports",
    },
    PilCatalogEntry {
        pil: "STD",
        wmo_prefix: "AT",
        title: "Satellite Tropical Disturbance Summary",
    },
    PilCatalogEntry {
        pil: "STO",
        wmo_prefix: "SX",
        title: "Road Condition Reports",
    },
    PilCatalogEntry {
        pil: "STQ",
        wmo_prefix: "BM",
        title: "Spot Forecast Request",
    },
    PilCatalogEntry {
        pil: "STW",
        wmo_prefix: "WW",
        title: "Canadian Storm Summary",
    },
    PilCatalogEntry {
        pil: "SVR",
        wmo_prefix: "WU",
        title: "Severe Thunderstorm Warning",
    },
    PilCatalogEntry {
        pil: "SVS",
        wmo_prefix: "WW",
        title: "Severe Weather Statement",
    },
    PilCatalogEntry {
        pil: "SWD",
        wmo_prefix: "XX",
        title: "Space Environment Warning Advistory",
    },
    PilCatalogEntry {
        pil: "SWE",
        wmo_prefix: "SR",
        title: "Estimated Snow Water Equivalent by Basin",
    },
    PilCatalogEntry {
        pil: "SWO",
        wmo_prefix: "AC",
        title: "Severe Storm Outlook Narrative",
    },
    PilCatalogEntry {
        pil: "SWS",
        wmo_prefix: "AW",
        title: "State Weather Summary",
    },
    PilCatalogEntry {
        pil: "SYN",
        wmo_prefix: "NZ",
        title: "Hot-Air Balloon Forecast for Colorado",
    },
    PilCatalogEntry {
        pil: "TAF",
        wmo_prefix: "FT",
        title: "Terminal Aerodrome Forecast",
    },
    PilCatalogEntry {
        pil: "TAP",
        wmo_prefix: "FA",
        title: "Terminal Alerting Products",
    },
    PilCatalogEntry {
        pil: "TAV",
        wmo_prefix: "FP",
        title: "Travelers Forecast Table",
    },
    PilCatalogEntry {
        pil: "TCA",
        wmo_prefix: "FK",
        title: "Tropical Cyclone Advisory",
    },
    PilCatalogEntry {
        pil: "TCD",
        wmo_prefix: "WT",
        title: "Tropical Cyclone Discussion",
    },
    PilCatalogEntry {
        pil: "TCE",
        wmo_prefix: "WT",
        title: "Tropical Cyclone Position Estimate",
    },
    PilCatalogEntry {
        pil: "TCM",
        wmo_prefix: "WT",
        title: "Marine/Aviation Tropical Cyclone Advisory",
    },
    PilCatalogEntry {
        pil: "TCP",
        wmo_prefix: "WT",
        title: "Public Tropical Cyclone Advisory",
    },
    PilCatalogEntry {
        pil: "TCS",
        wmo_prefix: "TX",
        title: "Satellite Tropical Cyclone Summary",
    },
    PilCatalogEntry {
        pil: "TCU",
        wmo_prefix: "WT",
        title: "Tropical Cyclone Update",
    },
    PilCatalogEntry {
        pil: "TCV",
        wmo_prefix: "WT",
        title: "Tropical Cyclone Watch/Warning",
    },
    PilCatalogEntry {
        pil: "TIB",
        wmo_prefix: "WE",
        title: "Tsunami Information Bulletin",
    },
    PilCatalogEntry {
        pil: "TID",
        wmo_prefix: "SO",
        title: "Tide Report",
    },
    PilCatalogEntry {
        pil: "TLS",
        wmo_prefix: "WE",
        title: "Tsunami Local Statement",
    },
    PilCatalogEntry {
        pil: "TMA",
        wmo_prefix: "SE",
        title: "Tsunami Tide/Seismic Message Acknowledgment",
    },
    PilCatalogEntry {
        pil: "TOE",
        wmo_prefix: "WO",
        title: "911 Telephone Outage Emergency",
    },
    PilCatalogEntry {
        pil: "TOR",
        wmo_prefix: "WF",
        title: "Tornado Warning",
    },
    PilCatalogEntry {
        pil: "TPT",
        wmo_prefix: "SX",
        title: "Temperature Precipitation Table",
    },
    PilCatalogEntry {
        pil: "TSM",
        wmo_prefix: "SE",
        title: "Tsunami Tide/Seismic Message",
    },
    PilCatalogEntry {
        pil: "TST",
        wmo_prefix: "NT",
        title: "Test Message",
    },
    PilCatalogEntry {
        pil: "TSU",
        wmo_prefix: "WE",
        title: "Tsunami Watch/Warning",
    },
    PilCatalogEntry {
        pil: "TVL",
        wmo_prefix: "FP",
        title: "Travelers Forecast",
    },
    PilCatalogEntry {
        pil: "TWB",
        wmo_prefix: "FR",
        title: "Transcribed Weather Broadcast",
    },
    PilCatalogEntry {
        pil: "TWD",
        wmo_prefix: "AC",
        title: "Tropical Weather Discussion",
    },
    PilCatalogEntry {
        pil: "TWO",
        wmo_prefix: "AC",
        title: "Tropical Weather Outlook and Summary",
    },
    PilCatalogEntry {
        pil: "TWS",
        wmo_prefix: "AC",
        title: "Tropical Weather Summary",
    },
    PilCatalogEntry {
        pil: "UJX",
        wmo_prefix: "UJ",
        title: "JSC Upper Air Soundings",
    },
    PilCatalogEntry {
        pil: "UVI",
        wmo_prefix: "AE",
        title: "Ultraviolet Index",
    },
    PilCatalogEntry {
        pil: "VAA",
        wmo_prefix: "FV",
        title: "Volcanic Activity Advisory",
    },
    PilCatalogEntry {
        pil: "VER",
        wmo_prefix: "FX",
        title: "Forecast Verification Statistics",
    },
    PilCatalogEntry {
        pil: "VFT",
        wmo_prefix: "NX",
        title: "Terminal Aerodrome Forecast Verification",
    },
    PilCatalogEntry {
        pil: "VGP",
        wmo_prefix: "PX",
        title: "Vector Graphic",
    },
    PilCatalogEntry {
        pil: "VOW",
        wmo_prefix: "WO",
        title: "Volcano Warning",
    },
    PilCatalogEntry {
        pil: "WA0",
        wmo_prefix: "WA",
        title: "Airmet (Pacific)",
    },
    PilCatalogEntry {
        pil: "WA1",
        wmo_prefix: "WA",
        title: "Airmet (Northeast US)",
    },
    PilCatalogEntry {
        pil: "WA2",
        wmo_prefix: "WA",
        title: "Airmet (Southeast US)",
    },
    PilCatalogEntry {
        pil: "WA3",
        wmo_prefix: "WA",
        title: "Airmet (North Central US)",
    },
    PilCatalogEntry {
        pil: "WA4",
        wmo_prefix: "WA",
        title: "Airmet (South Central US)",
    },
    PilCatalogEntry {
        pil: "WA5",
        wmo_prefix: "WA",
        title: "Airmet (US Rocky Mountains)",
    },
    PilCatalogEntry {
        pil: "WA6",
        wmo_prefix: "WA",
        title: "Airmet (US West Coast)",
    },
    PilCatalogEntry {
        pil: "WA7",
        wmo_prefix: "WA",
        title: "Airmet (Juneau Alaska)",
    },
    PilCatalogEntry {
        pil: "WA8",
        wmo_prefix: "WA",
        title: "Airmet (Anchorage Alaska)",
    },
    PilCatalogEntry {
        pil: "WA9",
        wmo_prefix: "WA",
        title: "Airmet (Fairbanks Alaska)",
    },
    PilCatalogEntry {
        pil: "WAC",
        wmo_prefix: "WA",
        title: "Airmet (Caribbean)",
    },
    PilCatalogEntry {
        pil: "WAR",
        wmo_prefix: "WO",
        title: "Space Environment Warning",
    },
    PilCatalogEntry {
        pil: "WAT",
        wmo_prefix: "WO",
        title: "Space Weather Message Watch",
    },
    PilCatalogEntry {
        pil: "WCL",
        wmo_prefix: "NW",
        title: "Watch Clearance Message",
    },
    PilCatalogEntry {
        pil: "WCN",
        wmo_prefix: "WW",
        title: "Watch County Notification",
    },
    PilCatalogEntry {
        pil: "WCR",
        wmo_prefix: "AX",
        title: "Weekly Weather and Crop Report",
    },
    PilCatalogEntry {
        pil: "WDA",
        wmo_prefix: "CX",
        title: "Weekly Data for Agriculture",
    },
    PilCatalogEntry {
        pil: "WEK",
        wmo_prefix: "FX",
        title: "27-day Space Weather Forecast",
    },
    PilCatalogEntry {
        pil: "WOU",
        wmo_prefix: "WO",
        title: "Watch Outline Update",
    },
    PilCatalogEntry {
        pil: "WPD",
        wmo_prefix: "IU",
        title: "Wind Profiler Data",
    },
    PilCatalogEntry {
        pil: "WRK",
        wmo_prefix: "NZ",
        title: "Local Work File",
    },
    PilCatalogEntry {
        pil: "WS1",
        wmo_prefix: "WS",
        title: "Sigmet (Northeast US)",
    },
    PilCatalogEntry {
        pil: "WS2",
        wmo_prefix: "WS",
        title: "Sigmet (Southeast US)",
    },
    PilCatalogEntry {
        pil: "WS3",
        wmo_prefix: "WS",
        title: "Sigmet (North Central US)",
    },
    PilCatalogEntry {
        pil: "WS4",
        wmo_prefix: "WS",
        title: "Sigmet (South central US)",
    },
    PilCatalogEntry {
        pil: "WS5",
        wmo_prefix: "WS",
        title: "Sigmet (US Rocky Mountains)",
    },
    PilCatalogEntry {
        pil: "WS6",
        wmo_prefix: "WS",
        title: "Sigmet (US West Coast)",
    },
    PilCatalogEntry {
        pil: "WS7",
        wmo_prefix: "WS",
        title: "Sigmet (Juneau Alaska)",
    },
    PilCatalogEntry {
        pil: "WS8",
        wmo_prefix: "WS",
        title: "Sigmet (Anchorage Alaska)",
    },
    PilCatalogEntry {
        pil: "WS9",
        wmo_prefix: "WS",
        title: "Sigmet (Fairbanks Alaska)",
    },
    PilCatalogEntry {
        pil: "WST",
        wmo_prefix: "WC",
        title: "Tropical Cyclone Sigmet",
    },
    PilCatalogEntry {
        pil: "WSV",
        wmo_prefix: "WV",
        title: "Volcanic Activity Sigmet",
    },
    PilCatalogEntry {
        pil: "WSW",
        wmo_prefix: "WW",
        title: "Winter Weather Message",
    },
    PilCatalogEntry {
        pil: "WTS",
        wmo_prefix: "NT",
        title: "Warning test Message",
    },
    PilCatalogEntry {
        pil: "WVM",
        wmo_prefix: "NW",
        title: "Warning Verification Message",
    },
    PilCatalogEntry {
        pil: "WWA",
        wmo_prefix: "NW",
        title: "Watch Status Report",
    },
    PilCatalogEntry {
        pil: "WWP",
        wmo_prefix: "WW",
        title: "Severe Thunderstorm Watch Probabilities",
    },
    PilCatalogEntry {
        pil: "ZFP",
        wmo_prefix: "FP",
        title: "Zone Forecast Product",
    },
];
